#!/usr/bin/env bash

alias aliases='gvim ~/scripts/bashrc_functions'

alias kssh='ssh -o PreferredAuthentications=keyboard-interactive'

alias habits='history | sed 's/^[[:space:]]*[0-9]*[[:space:]]*//' | sort | uniq -c | sort -n -r | head -n 10'

alias nat='sudo iptables -t nat'
alias iptables='sudo iptables'

alias inst='sudo aptitude install'
alias purge='sudo aptitude purge'
alias search='aptitude search'
alias upgrade='sudo aptitude upgrade'
alias show='aptitude show'

alias webserverhere='sudo python -m SimpleHTTPServer'

alias g=git

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
