#!/bin/sh

gg()
{
    declare -A aliases
    aliases["gid"]='/opt/development/gid'
    aliases["p"]='/opt/development/preflight/'
    aliases["qa"]='/opt/development/gid/qa/tests/browser/'
    aliases["dev"]='/home/juanibiapina/development/'
    aliases["d"]='/home/juanibiapina/development/'
    aliases["bb"]='/home/juanibiapina/development/brazil-build/'
    aliases["sc"]='/home/juanibiapina/development/alias/'
    aliases["t"]='/home/juanibiapina/development/time-machine/'
    aliases["a"]='/home/juanibiapina/development/alias/'
    aliases["do"]='/home/juanibiapina/Downloads/'
    aliases["cc"]='/home/juanibiapina/development/ccmonitor/'

    cd ${aliases[${1:-gid}]}
    pwd
}
