#!/usr/bin/env bash

alias kssh='ssh -o PreferredAuthentications=keyboard-interactive'

alias habits='history | sed 's/^[[:space:]]*[0-9]*[[:space:]]*//' | sort | uniq -c | sort -n -r | head -n 10'

alias nat='sudo iptables -t nat'
alias iptables='sudo iptables'

alias inst='sudo aptitude install'
alias purge='sudo aptitude purge'
alias search='aptitude search'
alias upgrade='sudo aptitude upgrade'
alias show='aptitude show'

alias webserverhere='sudo python -m SimpleHTTPServer'

alias g=git

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'

  alias grep='grep --color=auto'
  alias fgrep='fgrep --color=auto'
  alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# edit aliases
alias aliases='vi ~/development/alias/tools/bash/aliases'

# cat for code
alias catcode='highlight -s vim-dark -M'

alias run_allocation_iso='while sleep 1; do echo "Going ..."; curl -s "http://ft04.gid.gap.com:8000/invoke?operation=build&objectname=CruiseControl+Project:name=trunk-allocation.isolated.functional-test" | grep Invocation; done'
