#!/usr/bin/env bash

if [ -n "$PS1" ]; then

  BASEDIR=$(dirname $(readlink ${BASH_SOURCE[0]}))

  # Ubuntu stuff
  . "$BASEDIR/ubuntu"

  # Configuration options
  . "$BASEDIR/config"

  # Aliases
  . "$BASEDIR/aliases"

  # Include all functions
  for file in $BASEDIR/functions/*
  do
    . "$file"
  done;

  # Key bindings
  . "$BASEDIR/keybindings"

  # Start screen
  if [ -z "$STY" ]; then
    exec screen -RR
  fi

fi
