#!/usr/bin/env bash

if [ -n "$PS1" ]; then

  BASEDIR=$(dirname $(readlink ${BASH_SOURCE[0]}))

  # Ubuntu stuff
  . "$BASEDIR/ubuntu"

  # Configuration options
  . "$BASEDIR/config"

  # Aliases
  . "$BASEDIR/aliases"

  # Include all functions
  for file in $BASEDIR/functions/*
  do
    . "$file"
  done;

  # Key bindings
  . "$BASEDIR/keybindings"

  # Set current directory
  if [ -f "/tmp/last_dir" ]; then
    cd "$(cat /tmp/last_dir)"
  fi

  # Start screen
  if [ -z "$STY" ]; then
    exec screen -RR
  fi

fi
