#!/usr/bin/env bash

if [ -n "$PS1" ]; then

  BASEFILE=${BASH_SOURCE[0]}
  if [ -L "$BASEFILE" ]; then
    BASEFILE=$(readlink -f "$BASEFILE")
  fi
  BASEDIR=$(dirname ${BASEFILE})

  # Ubuntu stuff
  . "$BASEDIR/ubuntu"

  # Configuration options
  . "$BASEDIR/config"

  # Aliases
  . "$BASEDIR/aliases"

  # Include all functions
  for file in $BASEDIR/functions/*
  do
    . "$file"
  done;

  # Key bindings
  . "$BASEDIR/keybindings"

  # Start screen
  if [ -z "$STY" ]; then
    exec screen -RR
  fi

  # Fortune
  fortune -s -n 260 -a | cowsay

fi
