#!/bin/bash

export PATH=$PATH:~/bin

PS1='$( if [[ ${?#0} = "" ]]; then echo "\[\e[01;32m\]:) \[\e[00m\]"; else echo "\[\e[01;31m\]:( \[\e[00m\]" ; fi)'

HISTCONTROL=ignoredups:ignorespace
shopt -s histappend
HISTSIZE=3000
HISTFILESIZE=5000

shopt -s checkwinsize

prompt_function()
{
  echo $PWD > /tmp/last_dir
}

PROMPT_COMMAND=prompt_function
