" Load pathogen
source ~/.vim/bundle/vim-pathogen/autoload/pathogen.vim
 
" Force filetype off because Ubuntu already enabled it
filetype off

" Start pathgen (load bundles)
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" Use filetype plugin
filetype indent plugin on

" Use dark background
set bg=dark

" Use F2 to open NERDTree
noremap <silent> <F2> :NERDTreeToggle<Return>

" Fix meta mappings
" for i in range(65,90) + range(97,122)
"   let c = nr2char(i)
"   exec "map \e".c." <M-".c.">"
"   exec "map! \e".c." <M-".c.">"
" endfor

" FuzzyFinder mappings
set <M-F>=F
noremap <silent><M-S-f>f  :FufFile **/<CR>

" Use spaces instead of tabs
set expandtab
set smarttab
set tabstop=2
set shiftwidth=2

" Enable syntax highligh
syntax on

" Disable swap files
set noswf

" Set the undo to have a thousand entries
set undolevels=1000

" Improve the search
set ignorecase smartcase showmatch hlsearch incsearch

" Set mapping to navigate between open split windows
noremap <C-h> <C-w><Left>
noremap <C-j> <C-w><Down>
noremap <C-k> <C-w><Up>
noremap <C-l> <C-w><Right>

" Clojure options
let vimclojure#HighlightBuiltins=1
let vimclojure#ParenRainbow=1
