" Force filetype off because Ubuntu already enabled it
filetype off

let isVundleInstalled=1
let vundle_readme=expand('~/.vim/bundle/vundle/README.md')
if !filereadable(vundle_readme)
    echo "Installing Vundle.."
    echo ""
    silent !mkdir -p ~/.vim/bundle
    silent !git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
    let isVundleInstalled=0
endif

" Load vundle
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Configure vundle modules
Bundle 'gmarik/vundle'
Bundle 'L9'
Bundle 'FuzzyFinder'
Bundle 'scrooloose/nerdtree'
Bundle 'VimClojure'
Bundle 'scrooloose/syntastic'
Bundle 'tpope/vim-fugitive'
Bundle 'rodjek/vim-puppet'
Bundle 'klen/python-mode'
Bundle 'git://vim-latex.git.sourceforge.net/gitroot/vim-latex/vim-latex'

if isVundleInstalled == 0
    echo "Installing Bundles, please ignore key map error messages"
    echo ""
    :BundleInstall
endif

" Use filetype plugin
filetype indent plugin on

" Use F2 to open NERDTree
noremap <silent> <F2> :NERDTreeToggle<Return>

" Fix meta mappings
" for i in range(65,90) + range(97,122)
"   let c = nr2char(i)
"   exec "map \e".c." <M-".c.">"
"   exec "map! \e".c." <M-".c.">"
" endfor

" FuzzyFinder mappings
set <M-F>=F
noremap <silent><M-S-f>f  :FufFile **/<CR>

" Use spaces instead of tabs
set expandtab
set smarttab
set tabstop=2
set shiftwidth=2

" Enable syntax highligh
syntax on

" Disable swap files
set noswf

" Set the undo to have a thousand entries
set undolevels=1000

" Improve the search
set ignorecase smartcase showmatch hlsearch incsearch

" Set mapping to navigate between open split windows
noremap <C-h> <C-w><Left>
noremap <C-j> <C-w><Down>
noremap <C-k> <C-w><Up>
noremap <C-l> <C-w><Right>

" Clojure options
let vimclojure#HighlightBuiltins=1
let vimclojure#ParenRainbow=1
let vimclojure#WantNailgun=1

" Python options
let g:pymode_folding = 0

" NERD Tree options
let NERDTreeIgnore = ['\.pyc$']

" vim-latex options
let g:tex_flavor='latex'
let g:Tex_DefaultTargetFormat='pdf'
